---
jobs:

- name: configure-pipeline
  plan:
  - in_parallel:
    - get: pipeline-source
      trigger: true
      params: {depth: 1}
  - set_pipeline: self
    file: pipeline-source/ci/pipeline.yml

- name: scan-18fgsa-concourse-task
  plan:
  - in_parallel: &resources
    - get: weekly
      trigger: true
    - get: 18fgsa-concourse-task
      params:
        format: oci
      trigger: true
    - get: pipeline-source
      trigger: false
  - task: scan
    file: pipeline-source/ci/scan-container.yml
    params:
      IMAGE: 18fgsa/concourse-task
  - put: ecr-docker-reg
    params:
      image: 18fgsa-concourse-task/image.tar

  

resources:
- name: pipeline-source
  type: git
  source:
    uri: https://github.com/cloud-gov/container-scanning
    branch: inital-deploy
    paths: [ci/*]

- name: 18fgsa-concourse-task
  type: registry-image
  source:
    repository: 18fgsa/concourse-task
    tag: latest

- name: weekly
  type: time
  source:
    days: [Tuesday]

- name: ecr-docker-reg
  type: registry-image
  source:
    tag: latest
    aws_access_key_id: ((aws-key))
    aws_secret_access_key: ((aws-secret))
    repository: ((aws-repo))