---
jobs:

- name: configure-pipeline
  plan:
  - in_parallel:
    - get: pipeline-source
      trigger: true
      params: {depth: 1}
  - set_pipeline: self
    file: pipeline-source/ci/pipeline.yml

- name: scan-18fgsa-concourse-task
  plan:
  - in_parallel: &resources
    - get: weekly
      trigger: true
    - get: gsa-concourse-task
      params:
        format: oci
      trigger: true
    - get: scan-source
      trigger: false
  - task: scan
    file: scan-source/ci/scan-container.yml
    params:
      IMAGE: 18fgsa/concourse-task
  - put: ecr-concourse-task
    params:
      image: gsa-concourse-task/image.tar
      additional_tags: gsa-concourse-task/tag

- name: scan-18fgsa-s3-resource-simple
  plan:
  - in_parallel: &resources
    - get: weekly
      trigger: true
    - get: gsa-s3-resource-simple
      params:
        format: oci
      trigger: true
    - get: scan-source
      trigger: false
  - task: scan
    file: scan-source/ci/scan-container.yml
    params:
      IMAGE: 18fgsa/s3-resource-simple
  - put: ecr-s3-resource-simple
    params:
      image: gsa-s3-resource-simple/image.tar
      additional_tags: gsa-s3-resource-simple/tag

- name: scan-18fgsa-oracle-client
  plan:
  - in_parallel: &resources
    - get: weekly
      trigger: true
    - get: gsa-oracle-client
      params:
        format: oci
      trigger: true
    - get: scan-source
      trigger: false
  - task: scan
    file: scan-source/ci/scan-container.yml
    params:
      IMAGE: 18fgsa/oracle-client
  - put: ecr-oracle-client
    params:
      image: gsa-oracle-client/image.tar
      additional_tags: gsa-oracle-client/tag

- name: scan-18fgsa-sql-clients
  plan:
  - in_parallel: &resources
    - get: weekly
      trigger: true
    - get: gsa-sql-clients
      params:
        format: oci
      trigger: true
    - get: scan-source
      trigger: false
  - task: scan
    file: scan-source/ci/scan-container.yml
    params:
      IMAGE: 18fgsa/sql-clients
  - put: ecr-sql-clients
    params:
      image: gsa-sql-clients/image.tar
      additional_tags: gsa-sql-clients/tag

- name: terraform-plan-ecr
  plan:
  - in_parallel:
    - get: terraform-templates
      resource: terraform-config
      trigger: true
    - get: pipeline-tasks
  - task: terraform-plan
    file: terraform-templates/terraform/terraform-apply.yml
    params: &tf-ecr
      TERRAFORM_ACTION: plan
      TEMPLATE_SUBDIR: terraform/
      STACK_NAME: ecr
      S3_TFSTATE_BUCKET: ((tf-state-bucket))
      AWS_DEFAULT_REGION: us-gov-west-1
      TF_VAR_remote_state_bucket: ((tf-state-bucket))
      TF_VAR_tooling_stack_name: tooling
  - put: slack
    params:
      text_file: terraform-state/message.txt
      text:  |
        :terraform: $BUILD_JOB_NAME needs review
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: '#cg-platform'
      username: ((username))
      icon_url: https://avatars1.githubusercontent.com/u/7809479?v=3&s=40

- name: terraform-apply-ecr
  plan:
  - in_parallel:
    - get: terraform-templates
      resource: terraform-config
      passed: [terraform-plan-ecr]
      trigger: true
    - get: pipeline-tasks
  - task: terraform-apply
    file: terraform-templates/terraform/terraform-apply.yml
    params:
      <<: *tf-ecr
      TERRAFORM_ACTION: apply

- name: list-tags-concourse-task
  plan:
  - get: scan-source
    passed: [scan-18fgsa-concourse-task]
  - get: weekly
    trigger: true
  - task: list-images
    file: scan-source/ci/list-images.yml
    params:
      AWS_DEFAULT_REGION: us-gov-west-1
      IMAGE_REPOSITORY: concourse-task
      S3_TFSTATE_BUCKET: ((tf-state-bucket))
      STACK_NAME: ecr

- name: list-tags-oracle-client
  plan:
  - get: scan-source
    passed: [scan-18fgsa-oracle-client]
  - get: weekly
    trigger: true
  - task: list-images
    file: scan-source/ci/list-images.yml
    params:
      AWS_DEFAULT_REGION: us-gov-west-1
      IMAGE_REPOSITORY: oracle-client
      S3_TFSTATE_BUCKET: ((tf-state-bucket))
      STACK_NAME: ecr

- name: list-tags-sql-clients
  plan:
  - get: scan-source
    passed: [scan-18fgsa-sql-clients]
  - get: weekly
    trigger: true
  - task: list-images
    file: scan-source/ci/list-images.yml
    params:
      AWS_DEFAULT_REGION: us-gov-west-1
      IMAGE_REPOSITORY: sql-clients
      S3_TFSTATE_BUCKET: ((tf-state-bucket))
      STACK_NAME: ecr

- name: delete-tag-concourse-task
  plan:
  - get: scan-source
  - task: delete-image
    file: scan-source/ci/delete-image.yml
    params:
      AWS_DEFAULT_REGION: us-gov-west-1
      IMAGE_REPOSITORY: concourse-task

- name: scan-ecr-concourse-task
  plan:
  - get: image-tags-concourse-task
    trigger: true
  - get: weekly
    trigger: true
    passed: [list-tags-concourse-task]
  - get: scan-source
    trigger: false
    passed: [list-tags-concourse-task]
  - get: gsa-concourse-task
    params:
      format: oci
    resource: ecr-concourse-task
  - load_var: tags
    file: image-tags-concourse-task/tags-concourse-task.json
  - across:
    - var: tag
      values: ((.:tags))
    task: task-((.:tag))
    file: scan-source/ci/scan-ecr-container.yml
    params:
      IMAGE: "concourse-task:((.:tag))"
      AWS_DEFAULT_REGION: us-gov-west-1
      REGISTRY: ((aws-ecr-registry))

- name: scan-ecr-oracle-client
  plan:
  - get: image-tags-oracle-client
    trigger: true
  - get: weekly
    trigger: true
    passed: [list-tags-oracle-client]
  - get: scan-source
    trigger: false
    passed: [list-tags-oracle-client]
  - get: gsa-oracle-client
    params:
      format: oci
    resource: ecr-oracle-client
  - load_var: tags
    file: image-tags-oracle-client/tags-oracle-client.json
  - across:
    - var: tag
      values: ((.:tags))
    task: task-((.:tag))
    file: scan-source/ci/scan-ecr-container.yml
    params:
      IMAGE: "oracle-client:((.:tag))"
      AWS_DEFAULT_REGION: us-gov-west-1
      REGISTRY: ((aws-ecr-registry))

resources:
- name: pipeline-source
  type: git
  source:
    uri: https://github.com/cloud-gov/container-scanning
    branch: inital-deploy
    paths: [ci/*]

- name: scan-source
  type: git
  source:
    uri: https://github.com/cloud-gov/container-scanning
    branch: inital-deploy
    paths: ["ci/scan-container.sh",
            "ci/scan-container.yml",
            "ci/scan-ecr-container.sh",
            "ci/scan-ecr-container.yml",
            "ci/list-images.sh",
            "ci/list-images.yml",
            "ci/delete-image.sh",
            "ci/delete-image.yml"]

- name: terraform-config
  type: git
  source:
    uri: https://github.com/cloud-gov/container-scanning
    branch: inital-deploy
    paths: [terraform/*]

- name: pipeline-tasks
  type: git
  source:
    uri: https://github.com/cloud-gov/cg-pipeline-tasks.git
    branch: master

- name: gsa-concourse-task
  type: registry-image
  source:
    repository: 18fgsa/concourse-task
    semver_constraint: ">= 1.0.0"

- name: gsa-s3-resource-simple
  type: registry-image
  source:
    repository: 18fgsa/s3-resource-simple
    semver_constraint: ">= 1.0.0"

- name: gsa-oracle-client
  type: registry-image
  source:
    repository: 18fgsa/oracle-client
    semver_constraint: ">= 1.0.0"

- name: gsa-sql-clients
  type: registry-image
  source:
    repository: 18fgsa/sql-clients
    semver_constraint: ">= 1.0.0"

- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

- name: weekly
  type: time
  source:
    days: [Tuesday]

- name: ecr-concourse-task
  type: registry-image
  source:
    aws_access_key_id: ((aws-key))
    aws_secret_access_key: ((aws-secret))
    repository: concourse-task
    aws_region: us-gov-west-1
    semver_constraint: ">= 1.0.0"

- name: ecr-s3-resource-simple
  type: registry-image
  source:
    aws_access_key_id: ((aws-key))
    aws_secret_access_key: ((aws-secret))
    repository: s3-resource-simple
    aws_region: us-gov-west-1
    semver_constraint: ">= 1.0.0"

- name: ecr-oracle-client
  type: registry-image
  source:
    aws_access_key_id: ((aws-key))
    aws_secret_access_key: ((aws-secret))
    repository: oracle-client
    aws_region: us-gov-west-1
    semver_constraint: ">= 1.0.0"

- name: ecr-sql-clients
  type: registry-image
  source:
    aws_access_key_id: ((aws-key))
    aws_secret_access_key: ((aws-secret))
    repository: sql-clients
    aws_region: us-gov-west-1
    semver_constraint: ">= 1.0.0"

- name: image-tags-concourse-task
  type: s3-iam
  source:
    bucket: ((tf-state-bucket))
    versioned_file: ecr/tags-concourse-task.json
    region_name: us-gov-west-1

# - name: image-tags-s3-resource-simple
#   type: s3-iam
#   source:
#     bucket: ((tf-state-bucket))
#     versioned_file: ecr/tags-s3-resource-simple.json
#     region_name: us-gov-west-1

# - name: image-tags-oracle-client
#   type: s3-iam
#   source:
#     bucket: ((tf-state-bucket))
#     versioned_file: ecr/tags-oracle-client.json
#     region_name: us-gov-west-1

# - name: image-tags-sql-clients
#   type: s3-iam
#   source:
#     bucket: ((tf-state-bucket))
#     versioned_file: ecr/tags-sql-clients.json
#     region_name: us-gov-west-1

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource
